### ISSUE TITLE
Bus stop not supported

### ISSUE THREAD

**Issue by Wombosvideo** [dbrgn/fahrplan#24]
I got an error when I tried to use a close bus stop as "from". If it helps:
```
> fahrplan from "rorschacherberg post" to stgallen
#  | Station               | Platform | Date          | Time  | Duration | Chg. | Travel with | Occupancy |
------------------------------------------------------------------------------------------------------------
1  | Rorschacherberg, Post | Traceback (most recent call last):
  File "/usr/local/bin/fahrplan", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/fahrplan/main.py", line 201, in main
    tableprinter.print_line(cols_from)
  File "/usr/local/lib/python2.7/dist-packages/fahrplan/tableprinter.py", line 39, in print_line
    out = item.ljust(width) + self.separator
AttributeError: 'NoneType' object has no attribute 'ljust'
```
Parsing the bus stop's name seemed to have worked although there's still an error. The error also occurs on different devices (I tried Windows Bash and a Debian VServer)

**Comment by dbrgn** [comment]
That is fixed in the current development version. I'll have to do a release to PyPI soon.

**Comment by dbrgn** [comment]
Version 1.0.0 is released! https://pypi.python.org/pypi/fahrplan/1.0.0
