### ISSUE TITLE
IndexError in parser

### ISSUE THREAD

**Issue by The-Compiler** [dbrgn/fahrplan#32]
I forgot how to talk to `fahrplan` properly so I tried something and was greeted with a stacktrace:

```
$ fahrplan rapperswil 'rüti, steinstrasse' 
Traceback (most recent call last):
  File "/usr/bin/fahrplan", line 11, in <module>
    load_entry_point('fahrplan==1.0.0', 'console_scripts', 'fahrplan')()
  File "/usr/lib/python3.7/site-packages/fahrplan/main.py", line 94, in main
    args, language = parse_input(options.request)
  File "/usr/lib/python3.7/site-packages/fahrplan/parser.py", line 248, in parse_input
    data, language = _process_tokens(tokens)
  File "/usr/lib/python3.7/site-packages/fahrplan/parser.py", line 106, in _process_tokens
    process_stack()
  File "/usr/lib/python3.7/site-packages/fahrplan/parser.py", line 93, in process_stack
    key = keywords.get(stack[0])
IndexError: list index out of range
```

**Comment by dbrgn** [comment]
Good find, fixes welcome :slight
